package com.liming.livestage;
import android.Manifest;import android.app.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.os.Bundle;import android.view.*;import android.widget.*;
public final class MainActivity extends Activity implements LocalSimulator.Listener{
 private static final int REQ=7;private CameraPreview cam;private LocalSimulator sim;private TextView viewers,likes,gift;private LinearLayout chat;private boolean paused;
 public void onCreate(Bundle b){super.onCreate(b);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);build();sim=new LocalSimulator(this);showTerms();}
 private void build(){FrameLayout root=new FrameLayout(this);root.setBackgroundColor(Color.BLACK);cam=new CameraPreview(this);root.addView(cam,new FrameLayout.LayoutParams(-1,-1));
  LinearLayout top=new LinearLayout(this);top.setPadding(dp(12),dp(18),dp(12),0);top.setGravity(Gravity.CENTER_VERTICAL);TextView host=t("HOST  ·  直播训练",15,true);top.addView(host,new LinearLayout.LayoutParams(0,dp(48),1));viewers=t("128",13,true);top.addView(viewers,new LinearLayout.LayoutParams(dp(80),dp(48)));root.addView(top,new FrameLayout.LayoutParams(-1,dp(72)));
  TextView mark=t("LIVE STAGE · SIMULATION",12,true);mark.setTextColor(0xFFFFD166);mark.setGravity(Gravity.CENTER);mark.setBackground(bg(0xB0000000,18));FrameLayout.LayoutParams mp=new FrameLayout.LayoutParams(dp(220),dp(34));mp.gravity=Gravity.TOP|Gravity.CENTER_HORIZONTAL;mp.topMargin=dp(82);root.addView(mark,mp);
  gift=t("",14,true);gift.setTextColor(0xFFFFD166);FrameLayout.LayoutParams gp=new FrameLayout.LayoutParams(dp(280),dp(58));gp.gravity=Gravity.START|Gravity.CENTER_VERTICAL;gp.leftMargin=dp(12);root.addView(gift,gp);
  chat=new LinearLayout(this);chat.setOrientation(LinearLayout.VERTICAL);FrameLayout.LayoutParams cp=new FrameLayout.LayoutParams((int)(getResources().getDisplayMetrics().widthPixels*.78f),dp(300));cp.gravity=Gravity.START|Gravity.BOTTOM;cp.leftMargin=dp(12);cp.bottomMargin=dp(78);root.addView(chat,cp);
  likes=t("♥ 0",14,true);likes.setGravity(Gravity.CENTER);FrameLayout.LayoutParams lp=new FrameLayout.LayoutParams(dp(70),dp(48));lp.gravity=Gravity.END|Gravity.BOTTOM;lp.rightMargin=dp(8);lp.bottomMargin=dp(92);root.addView(likes,lp);
  LinearLayout bar=new LinearLayout(this);bar.setPadding(dp(5),dp(8),dp(5),dp(8));String[] labels={"弹幕","礼物","点赞","镜头","暂停","说明"};for(String s:labels){Button x=button(s);bar.addView(x,new LinearLayout.LayoutParams(0,dp(50),1));if(s.equals("弹幕"))x.setOnClickListener(v->sim.comment());if(s.equals("礼物"))x.setOnClickListener(v->sim.gift());if(s.equals("点赞"))x.setOnClickListener(v->sim.like());if(s.equals("镜头"))x.setOnClickListener(v->switchCam());if(s.equals("暂停"))x.setOnClickListener(v->{paused=!paused;if(paused)sim.stop();else sim.start();x.setText(paused?"继续":"暂停");});if(s.equals("说明"))x.setOnClickListener(v->legal());}FrameLayout.LayoutParams bp=new FrameLayout.LayoutParams(-1,dp(70));bp.gravity=Gravity.BOTTOM;root.addView(bar,bp);setContentView(root);}
 private void showTerms(){new AlertDialog.Builder(this).setTitle("使用确认").setMessage("本软件仅用于直播训练和影视演示。界面中的观众、人数、评论、点赞和礼物均为本地模拟，不代表真实互动或收入。应用不连接任何直播平台，模拟标识不可关闭。").setCancelable(false).setNegativeButton("退出",(d,w)->finish()).setPositiveButton("同意并进入",(d,w)->requestCam()).show();}
 private void legal(){new AlertDialog.Builder(this).setTitle("隐私与条款").setMessage("应用仅申请摄像头权限用于本地预览；不申请网络、定位、麦克风、相册或通讯录权限；不上传或保存摄像头画面。不得冒充真实平台或误导他人。LiveStage Studio 与任何第三方直播平台无隶属关系。").setPositiveButton("关闭",null).show();}
 private void requestCam(){if(checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.CAMERA},REQ);else cam.start();sim.start();}
 private void switchCam(){if(checkSelfPermission(Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED)Toast.makeText(this,cam.switchLens()?"前置镜头":"后置镜头",Toast.LENGTH_SHORT).show();}
 public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==REQ&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)cam.start();}
 protected void onResume(){super.onResume();if(checkSelfPermission(Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED)cam.start();if(sim!=null&&!paused)sim.start();}protected void onPause(){if(sim!=null)sim.stop();if(cam!=null)cam.stop();super.onPause();}
 public void stats(int v,long l){viewers.setText(String.valueOf(v));likes.setText("♥ "+l);}public void message(String u,String m){TextView x=t(u+"  "+m,13,false);x.setPadding(dp(8),dp(5),dp(8),dp(5));x.setBackground(bg(0x85000000,12));chat.addView(x,new LinearLayout.LayoutParams(-1,dp(42)));while(chat.getChildCount()>7)chat.removeViewAt(0);}public void gift(String u,String g,int c){gift.setText(u+"  送出 "+g+" × "+c);gift.setBackground(bg(0xD0202020,16));gift.postDelayed(()->{gift.setText("");gift.setBackgroundColor(Color.TRANSPARENT);},3000);}
 private TextView t(String s,int size,boolean bold){TextView x=new TextView(this);x.setText(s);x.setTextColor(Color.WHITE);x.setTextSize(size);x.setGravity(Gravity.CENTER_VERTICAL);x.setTypeface(null,bold?1:0);return x;}private Button button(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setTextSize(12);b.setPadding(0,0,0,0);b.setBackground(bg(0xFF292929,14));return b;}private GradientDrawable bg(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
